../_posts/2018-05-10-callback-and-state.markdown: src/Main.lhs
	pandoc -s -f markdown+lhs -t markdown-fenced_code_attributes src/Main.lhs > $@

run:
	stack build --exec callback-and-state

all: ../_posts/2018-05-10-callback-and-state.markdown run
